import type { UsageSnapshot } from "./types";

// Mock snapshot used to develop the dashboard UI independently of the
// collectors. Values mirror the examples in spec.md, with a few rows tuned to
// exercise every status color (green / amber / red / gray).

const checkedAt = "2026-06-03T20:46:00+09:00";

export const mockSnapshot: UsageSnapshot = {
  generatedAt: "2026-06-03T20:46:12+09:00",
  collectors: [
    { provider: "claude", ok: true, state: "ok", checkedAt, durationMs: 4120 },
    { provider: "codex", ok: true, state: "ok", checkedAt, durationMs: 11890 },
    { provider: "agy", ok: true, state: "ok", checkedAt, durationMs: 9230 },
    {
      provider: "grok",
      ok: false,
      state: "error",
      checkedAt: "2026-06-03T20:31:02+09:00",
      durationMs: 20000,
      error: "PTY timeout waiting for \"Monthly limit left\" (last data 15m ago)",
    },
  ],
  limits: [
    // ---- Claude ----
    {
      id: "claude:session",
      provider: "claude",
      providerLabel: "Claude Code",
      planLabel: "Max 200",
      accountLabel: "demo@example.com",
      scope: "Current session",
      window: "session",
      usedPercent: 0,
      remainingPercent: 100,
      resetLabel: "Resets 1:29am (Asia/Seoul)",
      status: "available",
      sourceCommand: "claude → /usage",
      sourceText:
        "Current session\n0% used\nResets 1:29am (Asia/Seoul)",
      checkedAt,
    },
    {
      id: "claude:week-all",
      provider: "claude",
      providerLabel: "Claude Code",
      planLabel: "Max 200",
      scope: "Current week (all models)",
      window: "weekly",
      usedPercent: 6,
      remainingPercent: 94,
      resetLabel: "Resets Jun 9, 4pm (Asia/Seoul)",
      status: "available",
      sourceCommand: "claude → /usage",
      sourceText:
        "Current week (all models)\n6% used\nResets Jun 9, 4pm (Asia/Seoul)",
      checkedAt,
    },
    {
      id: "claude:week-sonnet",
      provider: "claude",
      providerLabel: "Claude Code",
      planLabel: "Max 200",
      scope: "Current week (Sonnet only)",
      window: "weekly",
      usedPercent: 0,
      remainingPercent: 100,
      status: "available",
      sourceCommand: "claude → /usage",
      sourceText: "Current week (Sonnet only)\n0% used",
      checkedAt,
    },

    // ---- Codex ----
    {
      id: "codex:5h",
      provider: "codex",
      providerLabel: "Codex",
      planLabel: "ChatGPT",
      accountLabel: "demo@example.com",
      scope: "5h limit",
      window: "5h",
      usedPercent: 3,
      remainingPercent: 97,
      status: "available",
      statusLabel: "gpt-5.5 xhigh fast",
      sourceCommand: "codex --no-alt-screen",
      sourceText:
        "gpt-5.5 xhigh fast · Context 100% left · 5h 97% left · weekly 76% left",
      checkedAt,
    },
    {
      id: "codex:weekly",
      provider: "codex",
      providerLabel: "Codex",
      planLabel: "ChatGPT",
      scope: "Weekly limit",
      window: "weekly",
      usedPercent: 24,
      remainingPercent: 76,
      status: "available",
      statusLabel: "gpt-5.5 xhigh fast",
      sourceCommand: "codex --no-alt-screen",
      sourceText:
        "gpt-5.5 xhigh fast · Context 100% left · 5h 97% left · weekly 76% left",
      checkedAt,
    },
    {
      id: "codex:context",
      provider: "codex",
      providerLabel: "Codex",
      planLabel: "ChatGPT",
      scope: "Context window",
      window: "context",
      usedPercent: 0,
      remainingPercent: 100,
      status: "available",
      informational: true,
      sourceCommand: "codex --no-alt-screen",
      sourceText: "Context 100% left",
      checkedAt,
    },
    {
      id: "codex:spark-5h",
      provider: "codex",
      providerLabel: "Codex",
      planLabel: "ChatGPT",
      scope: "5h limit (Spark)",
      window: "5h",
      usedPercent: 4,
      remainingPercent: 96,
      status: "available",
      statusLabel: "gpt-5.3-codex-spark",
      sourceCommand: "codex --no-alt-screen -m gpt-5.3-codex-spark",
      sourceText:
        "gpt-5.3-codex-spark xhigh · Context 100% left · 5h 96% left · weekly 76% left",
      checkedAt,
    },

    // ---- Antigravity (grouped weekly + 5h quota) ----
    {
      id: "agy:gemini-models:weekly",
      provider: "agy",
      providerLabel: "Antigravity",
      planLabel: "Google AI Pro",
      accountLabel: "demo@example.com",
      scope: "Gemini Models",
      window: "weekly",
      usedPercent: 1,
      remainingPercent: 99,
      status: "available",
      resetLabel: "Refreshes in 47h 3m",
      sourceCommand: "agy local quota API",
      sourceText: "Gemini Models\nWeekly Limit\n99% remaining · Refreshes in 47h 3m",
      checkedAt,
    },
    {
      id: "agy:gemini-models:5h",
      provider: "agy",
      providerLabel: "Antigravity",
      planLabel: "Google AI Pro",
      scope: "Gemini Models",
      window: "5h",
      usedPercent: 82,
      remainingPercent: 18,
      status: "warning",
      resetLabel: "Refreshes in 4h 55m",
      sourceCommand: "agy local quota API",
      sourceText: "Gemini Models\nFive Hour Limit\n18% remaining · Refreshes in 4h 55m",
      checkedAt,
    },
    {
      id: "agy:claude-and-gpt-models:weekly",
      provider: "agy",
      providerLabel: "Antigravity",
      planLabel: "Google AI Pro",
      scope: "Claude and GPT Models",
      window: "weekly",
      usedPercent: 0,
      remainingPercent: 100,
      status: "available",
      statusLabel: "Quota available",
      sourceCommand: "agy local quota API",
      sourceText: "Claude and GPT Models\nWeekly Limit\nQuota available",
      checkedAt,
    },
    {
      id: "agy:claude-and-gpt-models:5h",
      provider: "agy",
      providerLabel: "Antigravity",
      planLabel: "Google AI Pro",
      scope: "Claude and GPT Models",
      window: "5h",
      usedPercent: 100,
      remainingPercent: 0,
      status: "exhausted",
      statusLabel: "Quota exhausted",
      sourceCommand: "agy local quota API",
      sourceText: "Claude and GPT Models\nFive Hour Limit\nQuota exhausted",
      checkedAt,
    },

    // ---- Grok (collector errored — last good data retained as stale) ----
    {
      id: "grok:monthly",
      provider: "grok",
      providerLabel: "Grok",
      planLabel: "SuperGrok",
      scope: "Monthly limit",
      window: "monthly",
      usedPercent: 44,
      remainingPercent: 56,
      status: "error",
      statusLabel: "stale",
      sourceCommand: "grok (launch footer)",
      sourceText: "Monthly limit left: 56%",
      checkedAt: "2026-06-03T20:31:02+09:00",
      error: "Collector failed on last refresh; showing previous value.",
    },
  ],
};
